swagger:
  enable: true

spring:
  thymeleaf:
    cache: false # 控制前端页面模板缓存，若设置为true则前端页面不能实时刷新
  data:
    mongodb:
      uri: mongodb://172.21.213.33/Portal
#      authentication-database: Portal
#      database: Portal
#      host: 222.192.7.75
#      port: 23266
#      username: ogmsPortal
#      password: 62e779183825

resourcePath: D:/upload201225
